// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psevcmsbrakzfnakcnur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzZXZjbXNicmFremZuYWtjbnVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NzIyMjMsImV4cCI6MjA2NzQ0ODIyM30.NI5CtJ8Vp563EKe2hlppKE8ZuivDleTaglUMmkz6Ifg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});